### ISSUE TITLE
GPU Memory Usage Issues

### ISSUE THREAD

**Issue by iamgroot42** [nimarb/pytorch_influence_functions#15]
Computations inside `s_test` seem to run out of memory when tensors are on a GPU device (within 3-4 iterations). Does it have to do with some memory not being freed properly in one of these functions? I've experimented with this with ridiculously small models and batch sizes

**Comment by iamgroot42** [comment]
Perhaps [this](https://github.com/nimarb/pytorch_influence_functions/blob/master/pytorch_influence_functions/influence_function.py#L48) definition should be encased in a `ch.no_grad()` ?

**Comment by HAoYifei996** [comment]
Hi, did you solve it? I'm having a similar issue.

**Comment by iamgroot42** [comment]
@HAoYifei996 yeah, I solved it. You can have a look at my fork of this repo [here](https://github.com/iamgroot42/pytorch_influence_functions): specifically the relevant changes [here](https://github.com/nimarb/pytorch_influence_functions/compare/master...iamgroot42:master)
